# Allows use container-based infrastructure
sudo: false
dist: trusty

# Project language
language: php

php:
  - "5.4"
  - "5.5"
  - "5.6"
  - "7.0"
  - "7.1"
  - "7.2"
  - "7.3"
  - "7.4"
  - "8.0"

matrix:
  fast_finish: true

# disable the default submodule logic
git:
  submodules: false

# use sed to replace the SSH URL with the public URL, then init and update submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

before_script:
  - composer install --no-suggest --prefer-dist --no-interaction

cache:
  directories:
    - $HOME/.cache/composer/files

script:
  - composer test

after_success:
  - test $TRAVIS_PHP_VERSION = "7.0" &&
    travis_retry composer coverage
